adap_kl_ctrl: true
backward_batch_size: 1
batch_size: 32
cliprange: 0.2
cliprange_value: 0.2
compare_steps: 1
early_stopping: false
forward_batch_size: null
gamma: 1
gradient_accumulation_steps: 1
horizon: 10000
init_kl_coef: 0.2
kl_penalty: kl
lam: 0.95
learning_rate: 8.0e-06
log_with: tensorboard
max_grad_norm: null
mini_batch_size: 32
model_name: /data/xyq/trl/non-toxical/llama-2-7b-hh-fim
optimize_cuda_cache: false
ppo_epochs: 4
ratio_threshold: 10.0
remove_unused_columns: true
score_clip: null
seed: 0
steps: 20000
target: 6
target_kl: 0.1
task_name: null
total_ppo_epochs: 625
tracker_project_name: trl
use_score_norm: false
use_score_scaling: false
vf_coef: 0.1
